unit PersonModel;
interface
uses MVCFramework.ActiveRecord;


type
  [MVCNameCase(ncLowerCase)]
  [MVCTable('Person')]
  TPerson = class(TMVCActiveRecord)
  private
    [MVCTableField('UserId', [foPrimaryKey, foAutoGenerated])]
    fId: Integer;
    [MVCTableField('FirstName')]
    fFirstName: String;
    [MVCTableField('LastName')]
    fLastName: String;
  public
    property Id: Integer read fId write fId;
    property FirstName: String read fFirstName write fFirstName;
    property LastName: String read fLastName write fLastName;
    constructor Create(Id: Integer; FirstName, LastName: String); reintroduce;
  end;

implementation

constructor TPerson.Create(Id:Integer;FirstName, LastName: String);
begin
  inherited Create;
  fId := Id;
  fFirstName := FirstName;
  fLastName := LastName;
end;


end.
